return {
    ["GangCreated"] = "",
    ["GangDisbanded"] = "",
    ["AddedMember"] = "",
    ["KickedMember"] = "",
    ["SetMemberRank"] = "",
    ["AddedRank"] = "",
    ["EditRank"] = "",
    ["RemovedRank"] = "",
    ["StartedWar"] = "",
    ["EndedWar"] = "",
    ["WarKill"] = "",
    ["RemovedGang"] = "",
    ["RemovedMoney"] = "",
    ["AddedMoney"] = "",
    ["TransferedOwnership"] = "",
    ["CreatedTurf"] = "",
    ["StartedTurfWar"] = "",
    ["EndedTurfWar"] = "",
    ["AddedStrike"] = "",
    ["RemovedStrike"] = "",
}